### ISSUE TITLE
kopf plugin fails to load for ElasticSearch 1.5.1

### ISSUE THREAD

**Issue by glenavery** [lmenezes/elasticsearch-kopf#266]
On fedora 21, using elasticsearch 1.5.1 and kopf 1.4.3 I get the following error in the elasticsearch log file. Kopf was working when I had an older version of elasticsearch (1.4.2)

[2015-04-24 09:32:49,341][WARN ][plugins                  ] [loghost3.rex.local] failed to load plugin from [file:/usr/share/elasticsearch/plugins/kopf/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [null]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:533)
        at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:408)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:116)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:152)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:213)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.NullPointerException
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:510)
        ... 7 more

**Comment by lmenezes** [comment]
@glenavery I think it's not kopf related. I just tried installing 1.4.3 on a 1.5.1 node, and all works fine:

```
[10:30] leonardo.menezes:elasticsearch-1.5.1/ $ ./bin/plugin -install lmenezes/elasticsearch-kopf/v1.4.3
-> Installing lmenezes/elasticsearch-kopf/v1.4.3...
Trying http://download.elasticsearch.org/lmenezes/elasticsearch-kopf/elasticsearch-kopf-v1.4.3.zip...
Trying http://search.maven.org/remotecontent?filepath=lmenezes/elasticsearch-kopf/v1.4.3/elasticsearch-kopf-v1.4.3.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/lmenezes/elasticsearch-kopf/v1.4.3/elasticsearch-kopf-v1.4.3.zip...
Trying https://github.com/lmenezes/elasticsearch-kopf/archive/v1.4.3.zip...
Downloading ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Installed lmenezes/elasticsearch-kopf/v1.4.3 into /Users/leonardo.menezes/Downloads/elasticsearch-1.5.1/plugins/kopf
Identified as a _site plugin, moving to _site structure ...
[10:30] leonardo.menezes:elasticsearch-1.5.1/ $ ./bin/elasticsearch
[2015-04-24 10:30:26,052][INFO ][node                     ] [Centurious] version[1.5.1], pid[11206], build[5e38401/2015-04-09T13:41:35Z]
[2015-04-24 10:30:26,052][INFO ][node                     ] [Centurious] initializing ...
[2015-04-24 10:30:26,058][INFO ][plugins                  ] [Centurious] loaded [], sites [kopf]
[2015-04-24 10:30:28,054][INFO ][node                     ] [Centurious] initialized
[2015-04-24 10:30:28,055][INFO ][node                     ] [Centurious] starting ...
[2015-04-24 10:30:28,144][INFO ][transport                ] [Centurious] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.2.39:9300]}
[2015-04-24 10:30:28,162][INFO ][discovery                ] [Centurious] elasticsearch/cj-vHUS-QbKgFYuzmdPjdA
[2015-04-24 10:30:31,940][INFO ][cluster.service          ] [Centurious] new_master [Centurious][cj-vHUS-QbKgFYuzmdPjdA][nb-lmenezes.local][inet[/192.168.2.39:9300]], reason: zen-disco-join (elected_as_master)
[2015-04-24 10:30:31,964][INFO ][http                     ] [Centurious] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.2.39:9200]}
[2015-04-24 10:30:31,964][INFO ][node                     ] [Centurious] started
[2015-04-24 10:30:31,980][INFO ][gateway                  ] [Centurious] recovered [0] indices into cluster_state
```

Could it be something related to permissions on the plugins folder or something like that?

**Comment by glenavery** [comment]
Thanks, I was doing a offline install and the folder structure was slightly incorrect, seems to work now

Sorry
