### ISSUE TITLE
java.net.SocketException: Protocol family unavailable

### ISSUE THREAD

**Issue by shashidharrao** [lmenezes/elasticsearch-kopf#327]
I am trying to upgrade elastic search 1.x to 2.1 , getting below error.  

i tried all these settings but it's still failing.

To bind to all IPv6/IPv4 addresses, you can use

network.bind_host: "0"
network.bind_host: "::"

To bind to IPv4 loopback (localhost) only

network.bind_host: "0.0.0.0"
together with JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses"

ERROR : 

[2015-11-29 11:55:55,866][WARN ][transport.netty          ] [Node1] exception caught on transport layer [[id: 0xfa429912]], closing connection
java.net.SocketException: Protocol family unavailable
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:435)
        at sun.nio.ch.Net.connect(Net.java:427)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:643)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:913)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:880)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:852)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:250)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:395)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-29 11:55:57,361][WARN ][transport.netty          ] [Node1] exception caught on transport layer [[id: 0xe44a1084]], closing connection
java.net.SocketException: Protocol family unavailable
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:435)
        at sun.nio.ch.Net.connect(Net.java:427)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:643)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:913)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:880)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:852)
        at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:250)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:395)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-29 11:55:57,836][INFO ][node                     ] [Node1] stopping ...
[2015-11-29 11:55:57,857][INFO ][node                     ] [Node1] stopped
[2015-11-29 11:55:57,857][INFO ][node                     ] [Node1] closing ...
[2015-11-29 11:55:57,861][INFO ][node                     ] [Node1] closed

**Comment by lmenezes** [comment]
@shashidharrao not really related to kopf. try the elastic search mailing list.

**Comment by shashidharrao** [comment]
sorry i sent it to wrong group.
